### ISSUE TITLE
AD secret engine returns ""returns “unable to find service account”?

### ISSUE THREAD

**Issue by Badrmoh** [hashicorp/vault-plugin-secrets-ad#25]

**Comment by Badrmoh** [comment]
For anyone facing the same issue, the main problem you might face is that you can't configure the filter to search in ldap. Vault api is fixed to use `userPrincipalName` and this won't work directly for all ldap servers. The way to solve this is by adding a proxy (openldap proxy) and map attributes in `slapd.conf` (after defining them in schema) using `rwm-map` attribute.

**Comment by james-miller** [comment]
Does anyone know if there's any other way around this problem?

It seems like a major downfall of the secrets engine if it isn't able to query active directory directly.

**Comment by jamesnyika** [comment]
Aw please Vault team... surely you can change this to just use the full DN or the user or at least search by CN or something more common  ?
