### ISSUE TITLE
Can I create an account in Active Directory using Active Directory secrets engine?

### ISSUE THREAD

**Issue by 2994186010** [hashicorp/vault-plugin-secrets-ad#38]
I want to create an account in Active Directory using Active Directory secret engine. However, there is no parameter such as "creation_statements" in the Active Directory secrets engine.

**Comment by tyrannosaurus-becks** [comment]
The AD secrets engine doesn't currently create service accounts. In roles, you map to existing ones. Docs are located [here](https://www.vaultproject.io/docs/secrets/ad/index.html).
