### ISSUE TITLE
instructions for quick test

### ISSUE THREAD

**Issue by vsevel** [hashicorp/vault-plugin-secrets-ad#40]
hello,

I looked at:
https://github.com/hashicorp/vault-plugin-secrets-ad/blob/master/plugin/backend_test.go

and was hoping to use it to do a quick test.
so I started a vault server, enabled the ad engine: vault secrets enable ad

then created the following config
```
vault write ad/config \
    binddn='euclid' \
    bindpass='password' \
    url='ldap://ldap.forumsys.com:389' \
    userdn='cn=read-only-admin,dc=example,dc=com'
```

but I get an error on the role:
```
vault write ad/roles/test_role service_account_name="tester@example.com" ttl="10"

Error writing data to ad/roles/test_role: Error making API request.

URL: PUT http://localhost:8200/v1/ad/roles/test_role
Code: 500. Errors:

* 1 error occurred:
	* LDAP Result Code 34 "Invalid DN Syntax": invalid DN
```

is that supposed to work?
if not, any instructions to achieve similar?

thanks

**Comment by jeffsanicola** [comment]
I think your issue is that your binddn isn't in the same format as the userdn field.  binddn, in my experience, needs to be the fully qualified DN in your directory (similar to how you have the userdn formatted).

**Comment by vsevel** [comment]
you are right. it was part of the issue. I believe that would not have worked anyway because the admin user needs to have read/write access.

I tried creating my own ldap server with osixia/docker-openldap:

start ldap server:
```
docker run --rm -p 389:389 -p 636:636 --name my-openldap-container --detach osixia/openldap:1.2.5
```

add ou=mathematicians, and person euler in that ou. 
check everything is correct:
```
docker exec my-openldap-container ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin
...
# euler, example.org
dn: uid=euler,dc=example,dc=org
uid: euler
sn: Euler
cn: Leonhard Euler
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top
mail: euler@example.org
ou: mathematicians

# mathematicians, example.org
dn: ou=mathematicians,dc=example,dc=org
uniqueMember: uid=euler,dc=example,dc=com
ou: mathematicians
cn: Mathematicians
objectClass: groupOfUniqueNames
objectClass: top
```

create vault:
```
docker run --rm -d --name=vault --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -e VAULT_TOKEN=myroot -e 'VAULT_ADDR=http://localhost:8200' vault

docker exec -it vault sh

vault secrets enable ad

vault write ad/config \
    binddn='cn=admin,dc=example,dc=org' \
    bindpass='admin' \
    url='ldap://10.0.0.5' \
    userdn='ou=mathematicians,dc=example,dc=org' \
    userattr='uid' \
    case_sensitive_names=false \
    insecure_tls=true
```

try to create ad role:
```
vault write ad/roles/test_role service_account_name="euler" ttl="10"

Error writing data to ad/roles/test_role: Error making API request.

URL: PUT http://localhost:8200/v1/ad/roles/test_role
Code: 500. Errors:

* 1 error occurred:
        * unable to find service account named euler in active directory, searches are case sensitive
```

there is no logging that we can activate i the plugin, which would have helped figuring out the exact ldap query its is doing.

any idea?

**Comment by jeffsanicola** [comment]
I use Active Directory in my environment so I'm not 100% sure if it'll translate to OpenLDAP.
However, I had to specify the user principal name in order for the accounts to be managed to be located.  

In your example I would expect something like "euler@example.org" to be defined in the service_account_name field.

Also, another thing to note, if you're going to try to rotate the root user password, currently it's required to be in the same OU as your managed accounts (userdn path).

**Comment by vsevel** [comment]
> In your example I would expect something like "[euler@example.org](mailto:euler@example.org)" to be defined in the service_account_name field.

I tried that with no success. I think the issue is related to the user principal name not being there in OpenLDAP. 
I am so surprised how backend_test.go is written. because ldap://ldap.forumsys.com:389 has no upn either.

**Comment by jeffsanicola** [comment]
There could be some other environmental factors in my case (child domain of a multi-tier forest) that requires the UPN be provided.

But, now that I think about it, I do recall, at least about a year ago, being informed that only AD LDAP was supported and generic LDAP functionality was not yet implemented.  Generic LDAP compatibility was a roadmap item at the time and, I think, dependent on more robust/compatible Go libraries.  I haven't had much of a need for generic LDAP so I haven't really paid much attention to the state of that functionality.

Hopefully somebody more familiar with the supported capabilities can chime in here.

**Comment by vsevel** [comment]
FYI I have posted also in the google group:
https://groups.google.com/forum/#!topic/vault-tool/qNE9TJ-TI3w

**Comment by jeffsanicola** [comment]
I just noticed...
dn: uid=euler,dc=example,dc=org
should be:
dn: uid=euler,ou=mathematicians,dc=example,dc=org

**Comment by vsevel** [comment]
got an answer in the google groups, confirming that the ad secret engine is only expected to wortk with AD.
