### ISSUE TITLE
Vault AD Engine Paths not working

### ISSUE THREAD

**Issue by iknowajosh** [hashicorp/vault-plugin-secrets-ad#64]
Hey yall anyone having a hard time using the Vault AD Engine and trying to setup a library?
I get an error:
Error writing data to ad/library/x-team: Error making API request.

URL: PUT https://vault.x.io/v1/ad/library/x-team
Code: 404. Errors:

1 error occurred:
  * unsupported path

This is my call:
vault write -f ad/library/x-team service_account_names="x-test-user@test.domain.com,vaultPOCSvc@test.domain.com" ttl=2h max_ttl=8h

FWIW - The act of creating a role does work.

Has the path been deprecated? Is it specific to a version of Vault? I am on?

We are serving: Vault 1.2.4+prem
My local install of the vault CLI is: Vault v1.3.2+ent

**Comment by tyrannosaurus-becks** [comment]
Hi! The check-in/check-out feature [went out with version 1.3](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#13-november-14th-2019) so it won't work until you upgrade.
